[package]
name = "compression"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "1.0.0"

[lib]
name = "compression"
crate_type = ["rlib","dylib"]
